# Generated by Django 3.2.4 on 2021-06-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='description',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
