# Generated by Django 3.2.4 on 2021-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20210616_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
